CREATE DATABASE IF NOT EXISTS lab14_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lab14_db;

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    image VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);